"use client";

import { useEffect, useState } from "react";
import { Archive, CheckCircle2, Loader2, MessageCircle, MessagesSquare, RefreshCw, Sparkles, UsersRound } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Props={onSaveItems:(items:any[])=>Promise<void>|void};
type Post={id:string;message:string;createdTime?:string;comments:number;reactions:number;shares:number};
type Comment={id:string;message:string;createdTime?:string;likeCount:number};
export default function AudienceVoice({onSaveItems}:Props){
 const[pages,setPages]=useState<any[]>([]);const[pageId,setPageId]=useState("");const[posts,setPosts]=useState<Post[]>([]);const[postId,setPostId]=useState("");const[comments,setComments]=useState<Comment[]>([]);const[loading,setLoading]=useState(false);const[analyzing,setAnalyzing]=useState(false);const[result,setResult]=useState<any>(null);const[notice,setNotice]=useState("");
 useEffect(()=>{fetch("/api/meta/pages",{cache:"no-store"}).then(r=>r.json()).then(d=>{const p=d.pages||[];setPages(p);if(p.length)setPageId(p[0].id)}).catch(()=>{})},[]);
 const page=pages.find(p=>p.id===pageId);const post=posts.find(p=>p.id===postId);
 async function loadPosts(){if(!pageId)return;setLoading(true);setResult(null);setComments([]);try{const r=await fetch(`/api/meta/posts?pageId=${encodeURIComponent(pageId)}&limit=50&includeInsights=0`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);const list=d.posts||[];setPosts(list);if(list.length)setPostId(list[0].id);setNotice(`${list.length} publicaciones disponibles.`)}catch(e:any){setNotice(e.message||"No fue posible cargar publicaciones.")}finally{setLoading(false)}}
 async function loadComments(){if(!pageId||!postId)return;setLoading(true);setResult(null);try{const r=await fetch(`/api/meta/comments?pageId=${encodeURIComponent(pageId)}&postId=${encodeURIComponent(postId)}&limit=100`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setComments(d.comments||[]);setNotice(`${(d.comments||[]).length} comentarios listos para analizar.`)}catch(e:any){setNotice(e.message||"No fue posible leer comentarios.")}finally{setLoading(false)}}
 async function analyze(){if(!comments.length)return;setAnalyzing(true);try{const r=await fetch("/api/comments/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pageName:page?.name,postText:post?.message,comments:comments.map(c=>c.message).filter(Boolean).slice(0,100)})});const d=await r.json();if(!r.ok)throw new Error(d.error);setResult(d);if(supabase)await supabase.from("efimero_audience_analyses").insert({page_id:pageId,page_name:page?.name,post_id:postId,sample_size:comments.length,analysis:d});setNotice("Voz de audiencia analizada. Las ideas ya pasaron por Compliance Meta.")}catch(e:any){setNotice(e.message||"No fue posible analizar comentarios.")}finally{setAnalyzing(false)}}
 async function saveIdeas(){if(!result?.ideas?.length)return;await onSaveItems(result.ideas.map((x:any)=>({id:crypto.randomUUID(),text:x.text,category:x.category||"Audiencia",format:"Texto",createdAt:new Date().toISOString(),source:"generated",sourcePageId:pageId,sourcePageName:page?.name,notes:`Voz de audiencia · ${x.reason||"tema detectado"}`,generationBatch:`audience-${Date.now()}`,extractionMetadata:{audienceTheme:x.theme,compliance:x.compliance}})));setNotice(`${result.ideas.length} ideas guardadas en Biblioteca.`)}
 return <>
  <div className="pageIntro audienceIntro"><div><span className="overline">BLOQUE 15 · AUDIENCE LANGUAGE</span><h1>La audiencia también escribe el brief</h1><p>Analiza comentarios reales para detectar lenguaje, temas y preguntas recurrentes; después conviértelos en textos nuevos sin copiar a nadie ni pedir interacción.</p></div><div className="audienceIcon"><MessagesSquare/></div></div>
  <section className="audienceSetup"><div className="audienceFields"><label><span>Página</span><select value={pageId} onChange={e=>{setPageId(e.target.value);setPosts([]);setComments([]);setResult(null)}}>{pages.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><button onClick={loadPosts} disabled={!pageId||loading}>{loading?<Loader2 className="spin"/>:<RefreshCw/>} Cargar posts</button></div>{posts.length>0&&<><label className="audiencePost"><span>Publicación a estudiar</span><select value={postId} onChange={e=>{setPostId(e.target.value);setComments([]);setResult(null)}}>{posts.map(p=><option key={p.id} value={p.id}>{(p.message||"Publicación visual / sin caption").slice(0,110)} · {p.comments} comentarios</option>)}</select></label><button className="audienceLoad" onClick={loadComments} disabled={!postId||loading}><MessageCircle/> Leer hasta 100 comentarios</button></>}</section>
  {notice&&<div className="audienceNotice"><CheckCircle2/>{notice}</div>}
  {comments.length>0&&<section className="audienceSample"><div className="audienceSampleHead"><div><UsersRound/><span><b>{comments.length}</b> comentarios recuperados</span></div><button onClick={analyze} disabled={analyzing}>{analyzing?<Loader2 className="spin"/>:<Sparkles/>} {analyzing?"Analizando…":"Analizar voz"}</button></div><div className="commentCloud">{comments.slice(0,12).map(c=><p key={c.id}>{c.message}</p>)}</div></section>}
  {result&&<><section className="audienceSummary"><span>LECTURA DE AUDIENCIA</span><h2>{result.summary}</h2><div className="audienceThemes">{(result.themes||[]).map((t:any)=><article key={t.label}><b>{t.label}</b><span>{t.signal}</span></article>)}</div><div className="audienceLanguage"><strong>Lenguaje que se repite</strong>{(result.language||[]).map((x:string)=><span key={x}>{x}</span>)}</div></section><section className="audienceIdeas"><div className="audienceIdeasHead"><div><span>TEXTOS DERIVADOS DEL INSIGHT</span><h2>Ideas nuevas, no respuestas copiadas</h2></div><button onClick={saveIdeas}><Archive/> Guardar ideas</button></div>{(result.ideas||[]).map((x:any,i:number)=><article key={i}><div><i>{String(i+1).padStart(2,"0")}</i><span>{x.category}</span><b>Meta {x.compliance?.score??"—"}/100</b></div><p>{x.text}</p><small>{x.reason}</small></article>)}</section></>}
 </>
}
