"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bot, CalendarDays, CheckCircle2, Loader2, Send, ShieldCheck, Sparkles, Target, WandSparkles } from "lucide-react";

type Proposal={date:string;time:string;category:string;text:string;reason:string;compliance:any;score:any};
type Props={onQueue:(items:any[])=>void};
type Page={id:string;name:string};

export default function AutonomousEditor({onQueue}:Props){
  const [pages,setPages]=useState<Page[]>([]);const [pageId,setPageId]=useState("");const [horizon,setHorizon]=useState(7);const [perDay,setPerDay]=useState(3);const [objective,setObjective]=useState("Equilibrado");const [busy,setBusy]=useState(false);const [queueBusy,setQueueBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [items,setItems]=useState<Proposal[]>([]);const [selected,setSelected]=useState<Set<number>>(new Set());
  useEffect(()=>{fetch("/api/meta/pages",{cache:"no-store"}).then(r=>r.json()).then(d=>{const next=(d.pages||[]).map((x:any)=>({id:String(x.id||x.page_id),name:String(x.name||x.page_name)}));setPages(next);if(next.length)setPageId(String(d.activePageId||next[0].id))}).catch(()=>{})},[]);
  const passCount=useMemo(()=>items.filter(x=>x.compliance?.status==="pass").length,[items]);
  async function run(){setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/editorial-agent/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pageId,horizonDays:horizon,perDay,objective,maxItems:8})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No fue posible ejecutar el agente.");const next=d.items||[];setItems(next);setSelected(new Set(next.map((x:any,i:number)=>x.compliance?.status==="pass"&&Number(x.score?.score||0)>=55?i:-1).filter((x:number)=>x>=0)));setMessage(d.message||`${next.length} propuestas construidas para ${d.pageName||"la página"}.`) }catch(e:any){setError(e?.message||"Falló el agente editorial.")}finally{setBusy(false)}}
  async function queue(){const chosen=items.filter((_,i)=>selected.has(i));if(!chosen.length)return;setQueueBusy(true);setError("");try{const r=await fetch("/api/editorial-agent/queue",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pageId,items:chosen})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No fue posible mandar las propuestas a Bandeja.");const local=(d.queued||[]).map((x:any)=>({id:x.id,date:String(x.publish_at||"").slice(0,10),time:String(x.publish_at||"").slice(11,16),category:x.category,text:x.text,format:"Texto",status:"Aprobado",pageId:x.page_id,pageName:x.page_name,compliance:x.compliance_data,autopilot:true}));onQueue(local);setMessage(`${d.queued?.length||0} textos PASS enviados a Bandeja.`)}catch(e:any){setError(e?.message||"No fue posible guardar la cola.")}finally{setQueueBusy(false)}}
  function toggle(i:number){setSelected(current=>{const next=new Set(current);next.has(i)?next.delete(i):next.add(i);return next})}
  return <>
    <div className="pageIntro"><div><span className="overline">BLOQUE 25 · AGENTE EDITORIAL AUTÓNOMO</span><h1>Que la máquina proponga; tú conservas el control</h1><p>Detecta huecos reales del calendario, consulta aprendizaje, fatiga y dataset, redacta textos y los pasa por Compliance antes de acercarlos a publicación.</p></div><div className="autonomousSafety"><ShieldCheck size={18}/><span>Sin publicación directa</span></div></div>
    <section className="autonomousHero"><div className="autonomousBot"><Bot size={34}/></div><div><span>AGENTE</span><h2>Calendario → contexto → propuesta → score → Compliance → Bandeja</h2><p>Nunca salta la revisión de políticas. El score describe compatibilidad editorial, no probabilidad de viralidad.</p></div></section>
    <section className="toolPanel"><div className="panelTitle actionTitle"><div><WandSparkles size={20}/><div><h2>Planificar el siguiente tramo</h2><p>Máximo 8 propuestas por ejecución para mantener revisión y coste bajo control.</p></div></div><button className="uiBtn uiBtnPrimary" onClick={run} disabled={busy||!pageId}>{busy?<Loader2 className="spin" size={16}/>:<Sparkles size={16}/>} Analizar y proponer</button></div>
      <div className="agentControls"><label><span>Página</span><select value={pageId} onChange={e=>setPageId(e.target.value)}>{pages.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label><span>Horizonte</span><select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}><option value={3}>3 días</option><option value={7}>7 días</option><option value={14}>14 días</option></select></label><label><span>Meta diaria</span><select value={perDay} onChange={e=>setPerDay(Number(e.target.value))}><option value={2}>2 textos</option><option value={3}>3 textos</option><option value={4}>4 textos</option><option value={6}>6 textos</option></select></label><label><span>Objetivo</span><select value={objective} onChange={e=>setObjective(e.target.value)}><option>Equilibrado</option><option>Compartibilidad</option><option>Comentarios</option><option>Variedad editorial</option></select></label></div>
      {(message||error)&&<div className={error?"calendarNotice error":"calendarNotice"}>{error?<AlertTriangle size={17}/>:<CheckCircle2 size={17}/>}<span>{error||message}</span></div>}
    </section>
    {items.length>0&&<section className="toolPanel agentResults"><div className="panelTitle actionTitle"><div><Target size={20}/><div><h2>Propuestas del agente</h2><p>{passCount} de {items.length} pasan Compliance local. Revisa razón y score antes de mandarlas a Bandeja.</p></div></div><button className="uiBtn uiBtnPrimary" onClick={queue} disabled={queueBusy||!selected.size}>{queueBusy?<Loader2 className="spin" size={16}/>:<Send size={16}/>} Enviar {selected.size} a Bandeja</button></div><div className="agentProposalGrid">{items.map((item,i)=><article className={selected.has(i)?"agentProposal selected":"agentProposal"} key={`${item.date}-${item.time}-${i}`}><button className="agentSelect" onClick={()=>toggle(i)} aria-label={selected.has(i)?"Quitar propuesta":"Seleccionar propuesta"}>{selected.has(i)?<CheckCircle2 size={18}/>:<span/>}</button><div className="agentProposalMeta"><span><CalendarDays size={13}/>{item.date} · {item.time}</span><span>{item.category}</span></div><p>{item.text}</p><small>{item.reason}</small><div className="agentProposalFooter"><b className={`scoreBadge ${Number(item.score?.score||0)>=70?"good":"mid"}`}>{Math.round(Number(item.score?.score||0))}/100</b><span className={item.compliance?.status==="pass"?"complianceMini pass":"complianceMini warn"}>{item.compliance?.status==="pass"?<ShieldCheck size={13}/>:<AlertTriangle size={13}/>} {String(item.compliance?.status||"review").toUpperCase()}</span></div></article>)}</div></section>}
  </>;
}
