"use client";

import { useEffect, useMemo, useState } from "react";
import { Archive, Beaker, Check, Copy, FlaskConical, Loader2, Save, Sparkles, Target, Trophy, WandSparkles } from "lucide-react";
import { supabase } from "@/lib/supabase";

type LibraryItem={id:string;text:string;category:string;source?:string;sourcePageId?:string;sourcePageName?:string;reactions?:number;comments?:number;shares?:number;reach?:number;notes?:string;format?:string;createdAt?:string;generationBatch?:string;extractionMetadata?:Record<string,unknown>};
type Props={library:LibraryItem[];onSaveItems:(items:any[])=>Promise<void>|void};
type Variant={id:string;text:string;label:string;hypothesis:string;selected:boolean;compliance?:any;reactions:number;comments:number;shares:number};
const metric=(v:Variant)=>v.reactions+v.comments*2+v.shares*4;
export default function CopyExperiments({library,onSaveItems}:Props){
 const [pages,setPages]=useState<any[]>([]);const[pageId,setPageId]=useState("");const[baseText,setBaseText]=useState("");const[dimension,setDimension]=useState("Hook");const[count,setCount]=useState(4);const[variants,setVariants]=useState<Variant[]>([]);const[generating,setGenerating]=useState(false);const[saving,setSaving]=useState(false);const[notice,setNotice]=useState("");
 useEffect(()=>{fetch("/api/meta/pages",{cache:"no-store"}).then(r=>r.json()).then(d=>{const p=d.pages||[];setPages(p);if(p.length)setPageId(p[0].id)}).catch(()=>{})},[]);
 const page=pages.find(p=>p.id===pageId);const candidates=useMemo(()=>library.filter(x=>x.text?.trim()&&x.source!=="reference"&&(!pageId||x.sourcePageId===pageId)).slice(0,40),[library,pageId]);
 const leader=variants.filter(v=>metric(v)>0).sort((a,b)=>metric(b)-metric(a))[0];
 async function generate(){if(!baseText.trim())return;setGenerating(true);setNotice("");try{const learning=(()=>{try{const m=JSON.parse(localStorage.getItem("efimero_learning_profiles")||"{}");return m?.[pageId]||null}catch{return null}})();const r=await fetch("/api/experiments/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:baseText,dimension,count,pageName:page?.name,learning})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No fue posible generar variantes.");setVariants((d.items||[]).map((x:any)=>({id:crypto.randomUUID(),text:x.text,label:x.label,hypothesis:x.hypothesis,selected:true,compliance:x.compliance,reactions:0,comments:0,shares:0})));setNotice("Variantes creadas y revisadas por Compliance Meta.")}catch(e:any){setNotice(e.message)}finally{setGenerating(false)}}
 async function save(){const chosen=variants.filter(v=>v.selected);if(!chosen.length)return;setSaving(true);const batch=`experiment-${Date.now()}`;try{await onSaveItems(chosen.map(v=>({id:crypto.randomUUID(),text:v.text,category:"Experimento",format:"Texto",createdAt:new Date().toISOString(),source:"generated",sourcePageId:pageId,sourcePageName:page?.name,notes:`Experimento ${dimension} · ${v.label}`,generationBatch:batch,extractionMetadata:{experimentDimension:dimension,hypothesis:v.hypothesis,compliance:v.compliance}})));if(supabase)await supabase.from("efimero_copy_experiments").insert({page_id:pageId,page_name:page?.name,base_text:baseText,dimension,variants:chosen,status:"draft"});setNotice(`${chosen.length} variantes guardadas en Biblioteca.`)}finally{setSaving(false)}}
 function setMetric(id:string,key:"reactions"|"comments"|"shares",value:number){setVariants(c=>c.map(v=>v.id===id?{...v,[key]:Math.max(0,value)}:v))}
 return <>
  <div className="pageIntro experimentIntro"><div><span className="overline">BLOQUE 14 · COPY LAB</span><h1>Experimentos de texto</h1><p>Prueba una sola variable a la vez: hook, longitud, tono o pregunta vs. afirmación. Así aprendes del copy sin confundir señales.</p></div><div className="experimentBadge"><FlaskConical/><span>A/B/n</span><small>solo texto</small></div></div>
  <section className="experimentSetup"><div className="experimentFields"><label><span>Página</span><select value={pageId} onChange={e=>setPageId(e.target.value)}>{pages.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span>Variable a probar</span><select value={dimension} onChange={e=>setDimension(e.target.value)}><option>Hook</option><option>Longitud</option><option>Tono</option><option>Pregunta vs afirmación</option></select></label><label><span>Variantes</span><select value={count} onChange={e=>setCount(Number(e.target.value))}><option value={3}>3</option><option value={4}>4</option><option value={5}>5</option></select></label></div><label className="experimentBase"><span>Texto base</span><textarea value={baseText} onChange={e=>setBaseText(e.target.value)} placeholder="Escribe un concepto o pega un texto de tu Biblioteca…"/></label>{candidates.length>0&&<div className="experimentExamples"><span>Usar como base:</span>{candidates.slice(0,6).map(x=><button key={x.id} onClick={()=>setBaseText(x.text)}>{x.text.slice(0,70)}{x.text.length>70?"…":""}</button>)}</div>}<button className="experimentGenerate" onClick={generate} disabled={generating||!baseText.trim()}>{generating?<Loader2 className="spin"/>:<Beaker/>} {generating?"Creando variantes…":"Generar experimento"}</button></section>
  {notice&&<div className="experimentNotice"><Sparkles size={16}/>{notice}</div>}
  {variants.length>0&&<section className="experimentResults"><div className="experimentResultsHead"><div><span>EXPERIMENTO ACTIVO</span><h2>{dimension}</h2><p>Edita, selecciona y luego registra métricas cuando las variantes hayan sido publicadas.</p></div><button onClick={save} disabled={saving||!variants.some(v=>v.selected)}>{saving?<Loader2 className="spin"/>:<Archive/>} Guardar seleccionadas</button></div><div className="variantGrid">{variants.map((v,i)=><article className={`variantCard ${v.selected?"selected":""} ${leader?.id===v.id?"leader":""}`} key={v.id}><button className="variantSelect" onClick={()=>setVariants(c=>c.map(x=>x.id===v.id?{...x,selected:!x.selected}:x))}>{v.selected?<Check/>:null}</button>{leader?.id===v.id&&<span className="leaderTag"><Trophy/> mejor señal registrada</span>}<div className="variantTop"><span>VARIANTE {String(i+1).padStart(2,"0")}</span><b>{v.label}</b></div><textarea value={v.text} onChange={e=>setVariants(c=>c.map(x=>x.id===v.id?{...x,text:e.target.value}:x))}/><p>{v.hypothesis}</p><div className="variantCompliance">Meta {v.compliance?.score??"—"}/100 · {v.compliance?.status||"pendiente"}</div><div className="variantMetrics"><label>👍<input type="number" min={0} value={v.reactions} onChange={e=>setMetric(v.id,"reactions",Number(e.target.value))}/></label><label>💬<input type="number" min={0} value={v.comments} onChange={e=>setMetric(v.id,"comments",Number(e.target.value))}/></label><label>↗<input type="number" min={0} value={v.shares} onChange={e=>setMetric(v.id,"shares",Number(e.target.value))}/></label></div><footer><span>Señal {metric(v).toLocaleString("es-MX")}</span><button onClick={()=>navigator.clipboard?.writeText(v.text)}><Copy/> Copiar</button></footer></article>)}</div></section>}
 </>
}
