"use client";

import { useState } from "react";
import { AlertTriangle, CheckCircle2, Gauge, Loader2, Search, ShieldCheck, Sparkles } from "lucide-react";

const dimensions:[string,string][]=[["compliance","Compliance"],["novelty","Novedad"],["historicalAlignment","Alineación histórica"],["historicalSignal","Señal histórica"],["lengthFit","Longitud"],["fatigueSafety","Anti-fatiga"]];
export default function EditorialScoring(){
  const [text,setText]=useState("A veces dejar de insistir también es una forma de cuidarte.");const [category,setCategory]=useState("Frases identificables");const [busy,setBusy]=useState(false);const [result,setResult]=useState<any>(null);const [error,setError]=useState("");
  async function evaluate(){if(!text.trim())return;setBusy(true);setError("");try{const r=await fetch("/api/editorial-score/evaluate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,category,targetWords:18})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No fue posible evaluar.");setResult(d.result)}catch(e:any){setError(e?.message||"Falló el scoring.")}finally{setBusy(false)}}
  return <>
    <div className="pageIntro"><div><span className="overline">BLOQUE 26 · SCORING EXPLICABLE</span><h1>Un número sin misterio</h1><p>Evalúa compatibilidad editorial con dimensiones visibles. No intenta adivinar viralidad ni reemplaza el resultado real después de publicar.</p></div><button className="uiBtn uiBtnPrimary" onClick={evaluate} disabled={busy||!text.trim()}>{busy?<Loader2 className="spin" size={16}/>:<Gauge size={16}/>} Calcular score</button></div>
    <div className="scoreWorkbench"><section className="toolPanel"><div className="panelTitle"><div><Sparkles size={20}/><div><h2>Texto a evaluar</h2><p>Prueba borradores antes de mandarlos a la Bandeja editorial.</p></div></div></div><label className="scoreCategory"><span>Categoría</span><select value={category} onChange={e=>setCategory(e.target.value)}><option>Frases identificables</option><option>Relaciones</option><option>Nostalgia</option><option>Preguntas</option><option>Humor</option><option>Vida cotidiana</option><option>Motivación ligera</option></select></label><textarea className="complianceTextarea" value={text} onChange={e=>setText(e.target.value)}/>{error&&<div className="calendarNotice error"><AlertTriangle size={16}/>{error}</div>}</section>
      <section className="toolPanel scoreResultPanel">{result?<><div className={`editorialScoreHero ${result.verdict}`}><Gauge size={30}/><div><span>SCORE EDITORIAL</span><strong>{Math.round(Number(result.score||0))}/100</strong><small>{result.verdict==="strong"?"Fuerte":result.verdict==="promising"?"Prometedor":result.verdict==="review"?"Revisar":"Débil"}</small></div></div><div className="scoreBars">{dimensions.map(([key,label])=><div className="scoreDimension" key={key}><div><span>{label}</span><b>{Math.round(Number(result.breakdown?.[key]||0))}</b></div><div className="scoreTrack"><span style={{width:`${Math.max(0,Math.min(100,Number(result.breakdown?.[key]||0)))}%`}}/></div></div>)}</div></>:<div className="scoreEmpty"><Gauge size={38}/><h3>Calcula el primer score</h3><p>Verás qué aporta y qué penaliza el texto.</p></div>}</section></div>
    {result&&<div className="scoreDetailGrid"><section className="toolPanel"><div className="panelTitle"><div><CheckCircle2 size={20}/><div><h2>Por qué suma</h2><p>Señales positivas detectadas.</p></div></div></div><div className="insightList">{(result.reasons||[]).map((x:string,i:number)=><p key={i}><CheckCircle2 size={15}/>{x}</p>)}{!result.reasons?.length&&<div className="emptyInline">Sin señales positivas suficientes todavía.</div>}</div></section><section className="toolPanel"><div className="panelTitle"><div><AlertTriangle size={20}/><div><h2>Qué revisar</h2><p>Penalizaciones o riesgos, no sentencias.</p></div></div></div><div className="insightList warning">{(result.warnings||[]).map((x:string,i:number)=><p key={i}><AlertTriangle size={15}/>{x}</p>)}{!result.warnings?.length&&<p><ShieldCheck size={15}/> No detectamos advertencias relevantes.</p>}</div></section></div>}
    {result?.nearest?.length>0&&<section className="toolPanel"><div className="panelTitle"><div><Search size={20}/><div><h2>Históricos cercanos</h2><p>Sirven para explicar el score y detectar copias accidentales.</p></div></div></div><div className="nearestGrid">{result.nearest.slice(0,6).map((x:any,i:number)=><article key={i}><div><span>{x.category}</span><b>{Math.round(Number(x.similarity||0)*100)}% semántico</b></div><p>{x.text}</p><small>{Math.round(Number(x.lexicalSimilarity||0)*100)}% coincidencia léxica · score histórico {Math.round(Number(x.performanceScore||0))}</small></article>)}</div></section>}
  </>;
}
