"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BookOpenCheck, BrainCircuit, CalendarDays, CheckCircle2, Clock3, FileText, Loader2, MessageCircle, RadioTower, RefreshCw, Share2, Sparkles, TrendingUp, WandSparkles } from "lucide-react";

type LibraryItem={id:string;text:string;source?:string;sourcePageId?:string;platformPostId?:string;category?:string;reactions?:number;comments?:number;shares?:number;factoryScore?:number};
type ScheduleItem={status:string;compliance?:any;pageId?:string;autopilot?:boolean};
type Props={library:LibraryItem[];schedule:ScheduleItem[];onOpenFactory:()=>void;onOpenLearning:()=>void};
type Post={id:string;message:string;createdTime?:string;reactions:number;comments:number;shares:number;reach:number};
const raw=(p:Post)=>p.reactions+p.comments*2+p.shares*4;const fmt=(n:number)=>new Intl.NumberFormat("es-MX",{notation:n>=1000000?"compact":"standard",maximumFractionDigits:1}).format(n);
export default function ExecutiveDashboard({library,schedule,onOpenFactory,onOpenLearning}:Props){
 const[pages,setPages]=useState<any[]>([]);const[pageId,setPageId]=useState("");const[posts,setPosts]=useState<Post[]>([]);const[loading,setLoading]=useState(false);const[updated,setUpdated]=useState("");
 useEffect(()=>{fetch("/api/meta/pages",{cache:"no-store"}).then(r=>r.json()).then(d=>{const p=d.pages||[];setPages(p);if(p.length)setPageId(p[0].id)}).catch(()=>{})},[]);
 useEffect(()=>{if(pageId)void refresh()},[pageId]);
 async function refresh(){setLoading(true);try{const r=await fetch(`/api/meta/posts?pageId=${encodeURIComponent(pageId)}&limit=100&includeInsights=0`,{cache:"no-store"});const d=await r.json();setPosts(r.ok?d.posts||[]:[]);setUpdated(new Date().toISOString())}finally{setLoading(false)}}
 const page=pages.find(p=>p.id===pageId);const lib=library.filter(x=>!pageId||x.sourcePageId===pageId);const enriched=new Set(lib.map(x=>x.platformPostId).filter(Boolean));const coverage=posts.length?Math.round(posts.filter(p=>p.message?.trim()||enriched.has(p.id)).length/posts.length*100):0;const totalShares=posts.reduce((n,p)=>n+p.shares,0),totalComments=posts.reduce((n,p)=>n+p.comments,0),totalReactions=posts.reduce((n,p)=>n+p.reactions,0);const best=[...posts].sort((a,b)=>raw(b)-raw(a))[0];const scheduled=schedule.filter(x=>!pageId||x.pageId===pageId);const pass=scheduled.filter(x=>x.compliance?.status==="pass").length;const complianceRate=scheduled.length?Math.round(pass/scheduled.length*100):100;
 const learning=useMemo(()=>{try{const m=JSON.parse(localStorage.getItem("efimero_learning_profiles")||"{}");return m?.[pageId]||null}catch{return null}},[pageId,lib.length]);
 const brief=[learning?.bestCategory?.label?`Generar una tanda de ${learning.bestCategory.label} usando ${learning.bestLength?.label||"la longitud aprendida"}.`:"Analizar aprendizaje para convertir el histórico en reglas de copy.",coverage<70?`La cobertura textual es ${coverage}%. Conviene seguir extrayendo texto de creatividades antes de sacar conclusiones fuertes.`:`Cobertura textual ${coverage}%: ya hay base suficiente para comparar patrones de copy.`,complianceRate<100?`Hay ${scheduled.length-pass} piezas del calendario que no están en PASS; revisarlas antes de publicar.`:"Las piezas revisadas del calendario no muestran bloqueos de Compliance Meta."];
 return <>
  <div className="pageIntro execIntro"><div><span className="overline">BLOQUE 16 · EXECUTIVE BRIEF</span><h1>El estado de la máquina de textos</h1><p>Una vista corta para decidir qué producir hoy, qué está aprendiendo la plataforma y dónde faltan datos.</p></div><div className="execControls"><select value={pageId} onChange={e=>setPageId(e.target.value)}>{pages.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button onClick={refresh} disabled={loading}>{loading?<Loader2 className="spin"/>:<RefreshCw/>} Actualizar</button></div></div>
  <div className="execKpis"><ExecKpi icon={<FileText/>} label="Cobertura textual" value={`${coverage}%`} note={`${posts.length} posts revisados`}/><ExecKpi icon={<Share2/>} label="Compartidos" value={fmt(totalShares)} note="última muestra"/><ExecKpi icon={<MessageCircle/>} label="Comentarios" value={fmt(totalComments)} note="última muestra"/><ExecKpi icon={<CheckCircle2/>} label="Compliance" value={`${complianceRate}%`} note={`${scheduled.length} piezas de calendario`}/></div>
  <section className="execBrief"><div className="execBriefTitle"><div><Sparkles/><span><b>Brief de hoy</b><small>{page?.name||"Página"} · {updated?new Date(updated).toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit"}):"sin actualizar"}</small></span></div><div className="execActions"><button onClick={onOpenLearning}><BrainCircuit/> Aprendizaje</button><button onClick={onOpenFactory}><WandSparkles/> Fábrica</button></div></div><div className="execBriefGrid">{brief.map((x,i)=><article key={i}><i>{String(i+1).padStart(2,"0")}</i><p>{x}</p></article>)}</div></section>
  <div className="execGrid"><section className="execPanel"><div className="execPanelHead"><TrendingUp/><div><h2>Señal editorial</h2><p>Último perfil de aprendizaje guardado.</p></div></div>{learning?<><strong className="execHeroValue">{learning.bestCategory?.label||"Mezcla abierta"}</strong><span className="execHeroNote">{learning.bestLength?.label||"Longitud variable"} · {learning.bestHook?.label||"Hooks variados"}</span><p>{learning.generationInstruction}</p></>:<div className="execEmpty"><BookOpenCheck/><span>Analiza el histórico en Aprendizaje para activar esta tarjeta.</span></div>}</section><section className="execPanel"><div className="execPanelHead"><RadioTower/><div><h2>Salud de datos</h2><p>Qué tan bien podemos estudiar los textos.</p></div></div><div className="execHealth"><div><span>Posts Meta</span><b>{posts.length}</b></div><div><span>Textos en Biblioteca</span><b>{lib.length}</b></div><div><span>Posts enriquecidos</span><b>{posts.filter(p=>enriched.has(p.id)).length}</b></div><div><span>Reacciones</span><b>{fmt(totalReactions)}</b></div></div>{coverage<50&&<div className="execWarning"><AlertTriangle/> Aún hay demasiadas piezas visuales sin texto extraído.</div>}</section></div>
  {best&&<section className="execTopPost"><Clock3/><div><span>PUBLICACIÓN CON MAYOR SEÑAL EN LA MUESTRA</span><p>{best.message?.trim()||lib.find(x=>x.platformPostId===best.id)?.text||"Publicación visual pendiente de texto"}</p><small>👍 {fmt(best.reactions)} · 💬 {fmt(best.comments)} · ↗ {fmt(best.shares)}</small></div></section>}
 </>
}
function ExecKpi({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <article className="execKpi"><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
