"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { AlertTriangle, BookmarkPlus, Check, ExternalLink, Eye, FileText, Image as ImageIcon, Loader2, Plus, RefreshCw, Search, ShieldCheck, Sparkles, Trash2, Upload } from "lucide-react";
import { supabase } from "@/lib/supabase";

type LibrarySource="manual"|"historical"|"generated"|"reference";
type LibraryItem={id:string;text:string;category:string;format:string;createdAt:string;source?:LibrarySource;sourceUrl?:string;notes?:string;reactions?:number;comments?:number;shares?:number;reach?:number;performanceScore?:number;favorite?:boolean;generationBatch?:string;sourcePageName?:string;sourceImageUrl?:string;extractionMetadata?:Record<string,unknown>;factoryScore?:number};
type Watch={id:string;name:string;page_url:string;notes?:string;enabled:boolean;created_at:string};
type Analysis={text:string;category:string;tone:string;hook:string;structure:string;theme:string;mechanism:string;summary:string;confidence:number};
type Generated={text:string;category:string;patternKept:string;changed:string;novelty:number;maxSimilarity:number;sourceSimilarity:number;datasetSimilarity:number;compliance:any;nearest?:any[];selected:boolean};
type Props={library:LibraryItem[];onSaveItems:(items:LibraryItem[])=>Promise<void>|void};

function normalize(text:string){return text.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim()}
function similarity(a:string,b:string){const A=new Set(normalize(a).split(" ").filter(Boolean)),B=new Set(normalize(b).split(" ").filter(Boolean));if(!A.size||!B.size)return 0;const i=[...A].filter(x=>B.has(x)).length;return i/new Set([...A,...B]).size}

export default function InspirationRadar({library,onSaveItems}:Props){
  const [watchlist,setWatchlist]=useState<Watch[]>([]);const [watchName,setWatchName]=useState("");const [watchUrl,setWatchUrl]=useState("");const [watchNotes,setWatchNotes]=useState("");
  const [sourceId,setSourceId]=useState("");const [sourceUrl,setSourceUrl]=useState("");const [text,setText]=useState("");const [imageDataUrl,setImageDataUrl]=useState("");const [imageName,setImageName]=useState("");const [analysis,setAnalysis]=useState<Analysis|null>(null);const [analyzing,setAnalyzing]=useState(false);const [message,setMessage]=useState("");
  const [mode,setMode]=useState("pattern-new-theme");const [count,setCount]=useState(6);const [generating,setGenerating]=useState(false);const [generated,setGenerated]=useState<Generated[]>([]);const [saving,setSaving]=useState(false);
  const references=useMemo(()=>library.filter(x=>x.source==="reference").slice(0,60),[library]);
  const selectedSource=watchlist.find(x=>x.id===sourceId)||null;
  useEffect(()=>{void loadWatchlist()},[]);
  async function loadWatchlist(){const db=supabase;if(!db)return;const {data}=await db.from("efimero_inspiration_watchlist").select("*").order("created_at",{ascending:false});setWatchlist((data||[]) as Watch[])}
  async function addWatch(){const name=watchName.trim(),url=watchUrl.trim();if(!name||!url)return;const db=supabase;if(!db){setMessage("Supabase no está configurado.");return}const {data,error}=await db.from("efimero_inspiration_watchlist").insert({name,page_url:url,notes:watchNotes.trim()||null}).select("*").single();if(error){setMessage(error.message);return}setWatchlist(c=>[data as Watch,...c]);setWatchName("");setWatchUrl("");setWatchNotes("")}
  async function removeWatch(id:string){const db=supabase;if(db)await db.from("efimero_inspiration_watchlist").delete().eq("id",id);setWatchlist(c=>c.filter(x=>x.id!==id));if(sourceId===id)setSourceId("")}
  async function handleFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;if(!file.type.startsWith("image/")){setMessage("Para esta entrada usa una captura de pantalla en JPG, PNG o WebP.");return}if(file.size>2_500_000){setMessage("La captura debe pesar menos de 2.5 MB para enviarla de forma segura al análisis.");return}const reader=new FileReader();reader.onload=()=>{setImageDataUrl(String(reader.result||""));setImageName(file.name);setAnalysis(null);setMessage("")};reader.readAsDataURL(file)}
  async function analyze(){if(!text.trim()&&!imageDataUrl){setMessage("Pega un texto o sube una captura.");return}setAnalyzing(true);setMessage("");try{const r=await fetch("/api/inspiration/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text, imageDataUrl,sourceName:selectedSource?.name||"Referencia externa",sourceUrl:sourceUrl||selectedSource?.page_url||""})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo analizar la referencia.");setAnalysis(d.analysis);if(!text.trim()&&d.analysis?.text)setText(d.analysis.text)}catch(e:any){setMessage(e?.message||"No se pudo analizar.")}finally{setAnalyzing(false)}}
  async function saveReference(){if(!analysis?.text)return;const item:LibraryItem={id:crypto.randomUUID(),text:analysis.text,category:analysis.category||"Otros",format:"Texto",createdAt:new Date().toISOString(),source:"reference",sourceUrl:sourceUrl||selectedSource?.page_url||undefined,sourcePageName:selectedSource?.name||undefined,notes:`${analysis.structure} · ${analysis.mechanism}`,favorite:false,extractionMetadata:{inspirationAnalysis:analysis,watchlistId:sourceId||null,sourceName:selectedSource?.name||null,capturedFrom:imageDataUrl?"screenshot":"text"}};await onSaveItems([item]);setMessage("Referencia guardada en Biblioteca como fuente externa.")}
  async function generate(){if(!analysis?.text){setMessage("Analiza primero la referencia.");return}setGenerating(true);setGenerated([]);setMessage("");try{const r=await fetch("/api/inspiration/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reference:analysis,count,mode})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudieron generar variaciones.");let items=(d.items||[]) as any[];if(items.length){try{const cr=await fetch("/api/compliance/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({texts:items.map(x=>x.text)})});const cd=await cr.json();if(cr.ok&&Array.isArray(cd.items))items=items.map((x,i)=>({...x,compliance:cd.items[i]||x.compliance}))}catch{}}
      const currentTexts=library.map(x=>x.text);setGenerated(items.map(x=>{const lexical=Math.max(0,...currentTexts.slice(0,1500).map(t=>similarity(t,x.text)));const novelty=Math.min(Number(x.novelty??100),Math.round((1-lexical)*100));return {...x,novelty,selected:x.compliance?.status==="pass"&&novelty>=40}}));
      const db=supabase;if(db)await db.from("efimero_inspiration_runs").insert({watchlist_id:sourceId||null,source_text:analysis.text,mode,result:{items}});
    }catch(e:any){setMessage(e?.message||"No se pudo generar.")}finally{setGenerating(false)}}
  async function saveGenerated(){const chosen=generated.filter(x=>x.selected&&x.compliance?.status==="pass"&&x.novelty>=40);if(!chosen.length){setMessage("Selecciona al menos un texto con Compliance PASS y novedad suficiente.");return}setSaving(true);try{const batch=`inspiration-${Date.now()}`;const items:LibraryItem[]=chosen.map(x=>({id:crypto.randomUUID(),text:x.text,category:x.category||analysis?.category||"General",format:"Texto",createdAt:new Date().toISOString(),source:"generated",favorite:false,generationBatch:batch,notes:`Radar de inspiración · patrón: ${x.patternKept} · cambio: ${x.changed}`,factoryScore:x.novelty,extractionMetadata:{inspiration:{sourceText:analysis?.text,sourceName:selectedSource?.name||null,sourceUrl:sourceUrl||selectedSource?.page_url||null,mode,novelty:x.novelty,sourceSimilarity:x.sourceSimilarity,datasetSimilarity:x.datasetSimilarity,patternKept:x.patternKept,changed:x.changed},compliance:x.compliance}}));await onSaveItems(items);setMessage(`${items.length} textos nuevos guardados en Biblioteca.`)}finally{setSaving(false)}}
  function useReference(item:LibraryItem){const meta:any=item.extractionMetadata||{};const a=meta.inspirationAnalysis as Analysis|undefined;setText(item.text);setSourceUrl(item.sourceUrl||"");setAnalysis(a||{text:item.text,category:item.category||"Otros",tone:"Referencia histórica",hook:item.text.split(/\s+/).slice(0,6).join(" "),structure:item.notes||"Patrón externo",theme:item.category||"General",mechanism:item.notes||"Identificación",summary:"Referencia guardada anteriormente.",confidence:.6});setImageDataUrl("");setImageName("");setGenerated([]);window.scrollTo({top:0,behavior:"smooth"})}
  const passCount=generated.filter(x=>x.compliance?.status==="pass"&&x.novelty>=40).length;
  return <>
    <div className="pageIntro"><div><span className="overline">BLOQUE 29 · RADAR DE INSPIRACIÓN</span><h1>Aprende patrones externos sin convertirlos en copias</h1><p>Guarda páginas de referencia, captura textos o screenshots, abstrae el mecanismo editorial y genera ideas nuevas que pasan por similitud + Compliance Meta.</p></div><div className="inspirationHeroBadge"><Eye size={17}/><div><strong>Monitoreo asistido</strong><span>Sin scraping masivo</span></div></div></div>
    <div className="inspirationMetrics"><Metric label="Páginas en Watchlist" value={watchlist.length}/><Metric label="Referencias guardadas" value={references.length}/><Metric label="Variaciones listas" value={passCount}/></div>
    <div className="inspirationGrid">
      <section className="toolPanel"><div className="panelTitle"><div><BookmarkPlus size={20}/><div><h2>Watchlist</h2><p>Organiza páginas que revisas. El Radar no scrapea su contenido automáticamente.</p></div></div></div><div className="watchForm"><input value={watchName} onChange={e=>setWatchName(e.target.value)} placeholder="Nombre de la página"/><input value={watchUrl} onChange={e=>setWatchUrl(e.target.value)} placeholder="https://facebook.com/..."/><input value={watchNotes} onChange={e=>setWatchNotes(e.target.value)} placeholder="Qué te interesa observar"/><button className="uiBtn uiBtnPrimary" onClick={addWatch}><Plus size={16}/> Agregar</button></div><div className="watchList">{watchlist.length?watchlist.map(w=><article key={w.id} className={sourceId===w.id?"watchItem active":"watchItem"}><button className="watchSelect" onClick={()=>{setSourceId(w.id);setSourceUrl(w.page_url)}}><strong>{w.name}</strong><span>{w.notes||"Sin notas"}</span></button><a href={w.page_url} target="_blank" rel="noreferrer" title="Abrir página"><ExternalLink size={16}/></a><button onClick={()=>removeWatch(w.id)} title="Eliminar"><Trash2 size={16}/></button></article>):<div className="emptyInline">Agrega páginas para tener a mano tus fuentes de inspiración.</div>}</div></section>
      <section className="toolPanel capturePanel"><div className="panelTitle"><div><Search size={20}/><div><h2>Capturar referencia</h2><p>Pega el copy o sube una captura si el texto vive dentro de una imagen.</p></div></div></div><label className="field"><span>Fuente</span><select value={sourceId} onChange={e=>{setSourceId(e.target.value);const w=watchlist.find(x=>x.id===e.target.value);if(w)setSourceUrl(w.page_url)}}><option value="">Referencia sin Watchlist</option>{watchlist.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select></label><label className="field"><span>URL de la publicación (opcional)</span><input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="Pega el permalink si lo tienes"/></label><textarea className="inspirationTextarea" value={text} onChange={e=>{setText(e.target.value);setAnalysis(null)}} placeholder="Pega aquí el texto de otra publicación…"/><div className="captureActions"><label className="uiBtn uiBtnSecondary fileLike"><Upload size={16}/> Subir captura<input type="file" accept="image/png,image/jpeg,image/webp" onChange={handleFile}/></label>{imageDataUrl&&<div className="imageAttached"><ImageIcon size={16}/><span>{imageName}</span><button onClick={()=>{setImageDataUrl("");setImageName("")}}>×</button></div>}<button className="uiBtn uiBtnPrimary" onClick={analyze} disabled={analyzing||(!text.trim()&&!imageDataUrl)}>{analyzing?<Loader2 className="spin" size={16}/>:<Sparkles size={16}/>} Analizar patrón</button></div>{message&&<div className="inlineNotice">{message}</div>}</section>
    </div>
    {analysis&&<section className="toolPanel inspirationAnalysis"><div className="panelTitle"><div><Eye size={20}/><div><h2>Patrón abstraído</h2><p>Esto es lo que utilizaremos como inspiración; no la redacción literal.</p></div></div><button className="uiBtn uiBtnSecondary" onClick={saveReference}><BookmarkPlus size={16}/> Guardar referencia</button></div><blockquote>{analysis.text}</blockquote><div className="analysisChips"><span>{analysis.category}</span><span>{analysis.tone}</span><span>{Math.round((analysis.confidence||0)*100)}% confianza</span></div><div className="patternGrid"><Pattern label="Hook" value={analysis.hook}/><Pattern label="Estructura" value={analysis.structure}/><Pattern label="Tema" value={analysis.theme}/><Pattern label="Mecanismo" value={analysis.mechanism}/></div><p className="analysisSummary">{analysis.summary}</p></section>}
    {analysis&&<section className="toolPanel variationPanel"><div className="panelTitle actionTitle"><div><Sparkles size={20}/><div><h2>Generar variaciones realmente nuevas</h2><p>Elige cuánto conservar del mecanismo original.</p></div></div><div className="uiActionRow"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="pattern-new-theme">Mismo patrón · tema nuevo</option><option value="same-theme-new-structure">Mismo tema · estructura nueva</option><option value="mechanism-only">Solo mecanismo psicológico</option></select><select value={count} onChange={e=>setCount(Number(e.target.value))}>{[3,6,9,12].map(n=><option value={n} key={n}>{n} textos</option>)}</select><button className="uiBtn uiBtnPrimary" onClick={generate} disabled={generating}>{generating?<Loader2 className="spin" size={16}/>:<Sparkles size={16}/>} Generar</button></div></div>{generated.length?<><div className="variationList">{generated.map((item,i)=>{const safe=item.compliance?.status==="pass"&&item.novelty>=40;return <article className={safe?"variationCard":"variationCard risky"} key={i}><label className="variationCheck"><input type="checkbox" checked={item.selected} disabled={!safe} onChange={e=>setGenerated(c=>c.map((x,j)=>j===i?{...x,selected:e.target.checked}:x))}/><span/></label><div className="variationBody"><div className="variationBadges"><span className={item.compliance?.status==="pass"?"pass":"warn"}>{item.compliance?.status==="pass"?<ShieldCheck size={13}/>:<AlertTriangle size={13}/>} {String(item.compliance?.status||"review").toUpperCase()}</span><span>{item.novelty}% novedad</span><span>{item.category}</span></div><p>{item.text}</p><small>Conserva: {item.patternKept} · Cambia: {item.changed}</small>{item.novelty<40&&<b className="similarityWarning">Demasiado cercano a una referencia o al dataset; no se puede guardar.</b>}</div></article>})}</div><div className="saveVariationBar"><span>{generated.filter(x=>x.selected).length} seleccionados</span><button className="uiBtn uiBtnPrimary" onClick={saveGenerated} disabled={saving||!generated.some(x=>x.selected)}>{saving?<Loader2 className="spin" size={16}/>:<Check size={16}/>} Guardar textos nuevos</button></div></>:<div className="emptyInline">Todavía no hay variaciones. El Radar prioriza novedad y Compliance antes de dejarlas entrar a tu Biblioteca.</div>}</section>}
    <section className="toolPanel"><div className="panelTitle"><div><FileText size={20}/><div><h2>Referencias recientes</h2><p>Fuentes externas ya guardadas. Sirven para estudiar patrones, no como ejemplos literales de la Fábrica.</p></div></div></div><div className="referenceGrid">{references.length?references.slice(0,18).map(r=><article key={r.id} className="referenceCard"><div><span>{r.sourcePageName||"Referencia externa"}</span>{r.sourceUrl&&<a href={r.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={14}/></a>}</div><p>{r.text}</p><small>{r.category} · {r.notes||"Patrón pendiente"}</small><button className="uiBtn uiBtnSmall uiBtnSecondary" onClick={()=>useReference(r)}>Usar patrón</button></article>):<div className="emptyInline">Todavía no hay referencias externas guardadas.</div>}</div></section>
  </>;
}
function Metric({label,value}:{label:string;value:number}){return <article className="opsMetric"><span>{label}</span><strong>{value}</strong></article>}
function Pattern({label,value}:{label:string;value:string}){return <div className="patternItem"><span>{label}</span><strong>{value||"—"}</strong></div>}
