"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BrainCircuit, CheckCircle2, Database, FlaskConical, Layers3, Loader2, RefreshCw, Send, ShieldCheck, Sparkles, WandSparkles } from "lucide-react";

type LibrarySource="manual"|"historical"|"generated"|"reference";
type LibraryItem={id:string;text:string;category:string;format:string;createdAt:string;source?:LibrarySource;sourceUrl?:string;notes?:string;reactions?:number;comments?:number;shares?:number;reach?:number;performanceScore?:number;favorite?:boolean;generationBatch?:string;sourcePageName?:string;sourceImageUrl?:string;extractionMetadata?:Record<string,unknown>;factoryScore?:number};
type Pattern={id:string;title:string;category:string;tone:string;mechanism:string;description:string;sample_size:number;avg_engagement_score:number;source_pages?:string[];updated_at?:string};
type Watch={id:string;name:string;page_url:string;last_synced_at?:string;sync_status?:string};
type Status={pages:number;watchlist?:Watch[];posts:number;analyzed:number;patternCount:number;ownDataset:number;patterns:Pattern[];lastRun?:any};
type Generated={text:string;category:string;rationale:string;patternUsed:string;compliance:any;novelty:number;editorialScore:number;duplicateRisk:boolean;externalSimilarity:number;ownSimilarity:number;nearestExternal?:any[];nearestOwn?:any[];selected?:boolean};
type Props={onSaveItems:(items:LibraryItem[])=>Promise<void>|void;onQueue:(items:any[])=>void;onOpenRadar:()=>void};

const categories=["","Fe y espiritualidad","Reflexión","Relaciones","Nostalgia","Motivación","Pregunta/reflexión","Humor","Vida cotidiana"];
const pad=(n:number)=>String(n).padStart(2,"0");
const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const nowTime=()=>{const d=new Date();return `${pad(d.getHours())}:${pad(d.getMinutes())}`};

export default function LearningAgent({onSaveItems,onQueue,onOpenRadar}:Props){
  const [status,setStatus]=useState<Status>({pages:0,posts:0,analyzed:0,patternCount:0,ownDataset:0,patterns:[]});
  const [loading,setLoading]=useState(true);const [training,setTraining]=useState(false);const [collecting,setCollecting]=useState(false);const [trainLimit,setTrainLimit]=useState(200);const [postsPerPage,setPostsPerPage]=useState(25);const [message,setMessage]=useState("");
  const [objective,setObjective]=useState("Crear textos breves, originales y emocionalmente claros para Facebook");const [category,setCategory]=useState("");const [count,setCount]=useState(6);const [exploration,setExploration]=useState(55);const [generating,setGenerating]=useState(false);const [generated,setGenerated]=useState<Generated[]>([]);const [saving,setSaving]=useState(false);
  const ready=useMemo(()=>status.posts>0&&status.patternCount>0,[status.posts,status.patternCount]);
  useEffect(()=>{void loadStatus()},[]);

  async function loadStatus(){setLoading(true);try{const r=await fetch("/api/learning-agent/status",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo cargar el Learning Agent.");setStatus(d)}catch(e:any){setMessage(e?.message||"No se pudo cargar el estado.")}finally{setLoading(false)}}
  async function runTraining(){const r=await fetch("/api/learning-agent/train",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({limit:trainLimit})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo actualizar el aprendizaje.");return d}
  async function train(){setTraining(true);setMessage("");try{const d=await runTraining();setMessage(`Aprendizaje actualizado: ${d.analyzedNow||0} posts nuevos analizados · ${d.patternsFound||0} patrones activos.`);await loadStatus()}catch(e:any){setMessage(e?.message||"Falló el aprendizaje.")}finally{setTraining(false)}}
  async function collectAndTrain(){const pages=status.watchlist||[];if(!pages.length){setMessage("Agrega páginas al Radar antes de recolectar.");return}setCollecting(true);setMessage(`Recolectando hasta ${postsPerPage} posts de ${pages.length} páginas…`);let synced=0,failed=0;try{for(const page of pages){try{let r=await fetch("/api/inspiration/brightdata",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({watchlistId:page.id,numPosts:postsPerPage})});let d=await r.json();if(!r.ok)throw new Error(d.error||"Falló la sincronización.");if(d.status==="processing"&&d.snapshotId){for(let attempt=0;attempt<10;attempt++){await new Promise(resolve=>setTimeout(resolve,3000));r=await fetch("/api/inspiration/brightdata",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({watchlistId:page.id,action:"poll",snapshotId:d.snapshotId})});d=await r.json();if(!r.ok)throw new Error(d.error||"Falló el snapshot.");if(d.status==="ready")break}}if(d.status==="ready")synced++;else failed++}catch{failed++}setMessage(`Recolectando páginas: ${synced+failed}/${pages.length} · correctas ${synced} · pendientes/error ${failed}`)}const d=await runTraining();setMessage(`Ciclo completo: ${synced}/${pages.length} páginas sincronizadas · ${d.analyzedNow||0} posts nuevos analizados · ${d.patternsFound||0} patrones activos.`);await loadStatus()}catch(e:any){setMessage(e?.message||"No se pudo completar recolección + aprendizaje.")}finally{setCollecting(false)}}
  async function generate(){if(!objective.trim())return;setGenerating(true);setGenerated([]);setMessage("");try{const r=await fetch("/api/learning-agent/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({objective,category,count,exploration})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo generar.");let items=(d.items||[]) as Generated[];
      if(items.length){try{const cr=await fetch("/api/compliance/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({texts:items.map(x=>x.text)})});const cd=await cr.json();if(cr.ok&&Array.isArray(cd.items))items=items.map((x,i)=>({...x,compliance:cd.items[i]||x.compliance}))}catch{}}
      setGenerated(items.map(item=>({...item,selected:item.compliance?.status==="pass"&&!item.duplicateRisk})));
    }catch(e:any){setMessage(e?.message||"Falló la generación.")}finally{setGenerating(false)}}
  async function saveSelected(){const selected=generated.filter(x=>x.selected&&x.compliance?.status==="pass"&&!x.duplicateRisk);if(!selected.length)return;setSaving(true);try{const batch=crypto.randomUUID();const items:LibraryItem[]=selected.map(item=>({id:crypto.randomUUID(),text:item.text,category:item.category||"General",format:"Texto",createdAt:new Date().toISOString(),source:"generated",favorite:false,generationBatch:batch,factoryScore:item.editorialScore,notes:`Learning Agent · ${item.patternUsed||"patrón aprendido"}`,extractionMetadata:{learningAgent:true,novelty:item.novelty,editorialScore:item.editorialScore,externalSimilarity:item.externalSimilarity,ownSimilarity:item.ownSimilarity,rationale:item.rationale}}));await onSaveItems(items);setMessage(`${items.length} copys guardados en Biblioteca.`)}finally{setSaving(false)}}
  function queueSelected(){const selected=generated.filter(x=>x.selected&&x.compliance?.status==="pass"&&!x.duplicateRisk);if(!selected.length)return;const queued=selected.map(item=>({id:crypto.randomUUID(),date:today(),time:nowTime(),category:item.category||"General",text:item.text,format:"Texto",status:"Borrador",compliance:item.compliance,similarity:Math.max(item.externalSimilarity||0,item.ownSimilarity||0),editorialScore:item.editorialScore,scoreData:{learningAgent:true,novelty:item.novelty,rationale:item.rationale}}));onQueue(queued);setMessage(`${queued.length} copys enviados a Bandeja como borradores.`)}
  function toggle(index:number){setGenerated(current=>current.map((item,i)=>i===index?{...item,selected:!item.selected}:item))}

  return <>
    <div className="pageIntro learningAgentIntro"><div><span className="overline">BLOQUE 30 · LEARNING AGENT</span><h1>Aprende patrones sin copiar publicaciones</h1><p>Convierte los posts sincronizados del Radar en patrones editoriales abstractos y mézclalos con la memoria propia de Efímero. Es aprendizaje continuo con RAG, no fine-tuning del modelo.</p></div><button className="uiBtn uiBtnSecondary" onClick={onOpenRadar}><RefreshCw size={16}/> Abrir Radar</button></div>
    {message&&<div className="inlineNotice">{message}</div>}
    <div className="learningAgentMetrics">
      <article><span>Páginas vigiladas</span><strong>{loading?"—":status.pages}</strong><small>fuentes activas</small></article>
      <article><span>Posts externos</span><strong>{loading?"—":status.posts}</strong><small>sincronizados</small></article>
      <article><span>Analizados</span><strong>{loading?"—":status.analyzed}</strong><small>memoria externa</small></article>
      <article><span>Patrones</span><strong>{loading?"—":status.patternCount}</strong><small>clusters activos</small></article>
      <article><span>Memoria propia</span><strong>{loading?"—":status.ownDataset}</strong><small>RAG Efímero</small></article>
    </div>

    <section className="toolPanel learningTrainPanel"><div className="panelTitle actionTitle"><div><BrainCircuit size={20}/><div><h2>Recolectar y aprender</h2><p>Puede sincronizar varias páginas con Bright Data y después convertir sus posts en patrones editoriales.</p></div></div><div className="uiActionRow"><select value={postsPerPage} onChange={e=>setPostsPerPage(Number(e.target.value))}>{[10,25,50].map(n=><option key={n} value={n}>{n} por página</option>)}</select><select value={trainLimit} onChange={e=>setTrainLimit(Number(e.target.value))}>{[100,200,300,400].map(n=><option key={n} value={n}>Analizar {n}</option>)}</select><button className="uiBtn uiBtnSecondary" onClick={train} disabled={training||collecting||status.posts===0}>{training?<Loader2 className="spin" size={16}/>:<BrainCircuit size={16}/>} Solo aprender</button><button className="uiBtn uiBtnPrimary" onClick={collectAndTrain} disabled={collecting||training||status.pages===0}>{collecting?<Loader2 className="spin" size={16}/>:<RefreshCw size={16}/>} Recolectar + aprender</button></div></div>
      <div className="learningFlow"><span>Bright Data</span><b>→</b><span>Varias páginas</span><b>→</b><span>Analyzer</span><b>→</b><span>Embeddings</span><b>→</b><span>Clusters</span><b>→</b><span>RAG</span></div><div className="learningCostNote">Máximo solicitado en este ciclo: {(status.watchlist||[]).length*postsPerPage} registros externos. Bright Data puede cobrar según tu plan; Efímero no sincroniza automáticamente sin que pulses el botón.</div>
      {status.lastRun&&<small className="learningLastRun">Última ejecución: {new Date(status.lastRun.created_at).toLocaleString("es-MX")} · {Number(status.lastRun.patterns_found||0)} patrones</small>}
      {!status.posts&&<div className="emptyInline"><AlertTriangle size={17}/> Sincroniza primero publicaciones de varias páginas desde Radar.</div>}
    </section>

    <section className="toolPanel"><div className="panelTitle"><div><Layers3 size={20}/><div><h2>Patrones aprendidos</h2><p>No son textos guardados para copiar: son estructuras, tonos y mecanismos detectados en varias fuentes.</p></div></div></div><div className="learningPatternGrid">{status.patterns.map(pattern=><article key={pattern.id}><div className="learningPatternTop"><span>{pattern.category||"General"}</span><b>{Math.round(Number(pattern.avg_engagement_score||0))}/100</b></div><h3>{pattern.title}</h3><p>{pattern.description||pattern.mechanism}</p><div className="learningPatternMeta"><span>{pattern.sample_size} posts</span><span>{Array.isArray(pattern.source_pages)?pattern.source_pages.length:0} páginas</span><span>{pattern.tone||"tono mixto"}</span></div></article>)}{!status.patterns.length&&<div className="emptyInline"><Database size={17}/> Actualiza aprendizaje para descubrir los primeros patrones.</div>}</div></section>

    <section className="toolPanel learningGeneratePanel"><div className="panelTitle"><div><WandSparkles size={20}/><div><h2>Generar con aprendizaje</h2><p>La voz propia pesa más que las fuentes externas. El Radar aporta patrones; Efímero aporta identidad.</p></div></div><div className="learningWeights"><span><b>50%</b> voz propia</span><span><b>30%</b> patrones</span><span><b>20%</b> exploración</span></div></div>
      <div className="learningGeneratorControls"><label><span>Objetivo</span><textarea value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Qué quieres generar…"/></label><label><span>Categoría</span><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c||"all"} value={c}>{c||"Automática"}</option>)}</select></label><label><span>Cantidad</span><select value={count} onChange={e=>setCount(Number(e.target.value))}>{[3,6,9,12].map(n=><option key={n}>{n}</option>)}</select></label><label className="learningRange"><span>Exploración <b>{exploration}%</b></span><input type="range" min={0} max={100} step={5} value={exploration} onChange={e=>setExploration(Number(e.target.value))}/><small>{exploration<35?"Más conservador":exploration>70?"Más experimental":"Equilibrado"}</small></label></div>
      <button className="uiBtn uiBtnPrimary wide" onClick={generate} disabled={generating||!ready}>{generating?<Loader2 className="spin" size={16}/>:<Sparkles size={16}/>} Generar con inteligencia combinada</button>
    </section>

    {!!generated.length&&<section className="toolPanel"><div className="panelTitle actionTitle"><div><FlaskConical size={20}/><div><h2>Copys propuestos</h2><p>Solo pueden salir de aquí los que estén en PASS y no tengan riesgo de similitud.</p></div></div><div className="uiActionRow"><button className="uiBtn uiBtnSecondary" onClick={saveSelected} disabled={saving||!generated.some(x=>x.selected)}>{saving?<Loader2 className="spin" size={16}/>:<Database size={16}/>} Guardar en Biblioteca</button><button className="uiBtn uiBtnPrimary" onClick={queueSelected} disabled={!generated.some(x=>x.selected)}><Send size={16}/> Enviar a Bandeja</button></div></div><div className="learningGeneratedList">{generated.map((item,index)=>{const safe=item.compliance?.status==="pass"&&!item.duplicateRisk;return <article className={safe?"learningGeneratedCard":"learningGeneratedCard risky"} key={`${index}-${item.text.slice(0,20)}`}><label className="variationCheck"><input type="checkbox" checked={Boolean(item.selected)} disabled={!safe} onChange={()=>toggle(index)}/><span/></label><div><div className="learningGeneratedBadges"><span className={item.compliance?.status==="pass"?"pass":"warn"}>{item.compliance?.status==="pass"?<CheckCircle2 size={12}/>:<ShieldCheck size={12}/>} {String(item.compliance?.status||"review").toUpperCase()}</span><span>{item.novelty}% novedad</span><span>Score {item.editorialScore}</span>{item.duplicateRisk&&<span className="warn"><AlertTriangle size={12}/> similitud alta</span>}</div><p>{item.text}</p><small>{item.rationale}</small><div className="learningGeneratedMeta"><span>Patrón: {item.patternUsed||"—"}</span><span>Externo: {Math.round(Number(item.externalSimilarity||0)*100)}%</span><span>Propio: {Math.round(Number(item.ownSimilarity||0)*100)}%</span></div></div></article>})}</div></section>}
  </>;
}
