"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, ExternalLink, Loader2, RefreshCw, Settings2, ShieldCheck, Wrench } from "lucide-react";

export default function QualityCenter(){
  const [result,setResult]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{void run()},[]);
  async function run(){setBusy(true);setError("");try{const r=await fetch("/api/quality/audit",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo ejecutar la auditoría.");setResult(d.result)}catch(e:any){setError(e?.message||"Falló la auditoría.")}finally{setBusy(false)}}
  const checks=result?.checks||[];return <>
    <div className="pageIntro"><div><span className="overline">BLOQUE 28 · QA + UX FINAL</span><h1>La V1 debe ser operable, no solo bonita</h1><p>Audita autenticación, tokens, publicación, Compliance, automatización, dataset y deuda de configuración antes de dejar que el sistema trabaje solo.</p></div><button className="uiBtn uiBtnPrimary" onClick={run} disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<RefreshCw size={16}/>} Ejecutar auditoría</button></div>
    {error&&<div className="calendarNotice error"><AlertTriangle size={16}/>{error}</div>}
    {result&&<><section className={`qualityHero ${result.level}`}><div className="qualityScore"><ShieldCheck size={30}/><div><span>PREPARACIÓN V1</span><strong>{result.score}/100</strong><small>{result.level==="ready"?"Lista":result.level==="good"?"Buena, con detalles":"Necesita atención"}</small></div></div><div className="qualitySummary"><p><b>{checks.filter((x:any)=>x.status==="pass").length}</b> checks correctos</p><p><b>{checks.filter((x:any)=>x.status==="warn").length}</b> advertencias</p><p><b>{checks.filter((x:any)=>x.status==="fail").length}</b> críticos</p></div></section><div className="qualityGrid">{checks.map((x:any)=><article className={`qualityCheck ${x.status}`} key={x.id}><div>{x.status==="pass"?<CheckCircle2/>:<AlertTriangle/>}</div><span>{x.label}</span><strong>{x.status==="pass"?"OK":x.status==="warn"?"REVISAR":"CRÍTICO"}</strong><small>{x.detail}</small></article>)}</div></>}
    <div className="qualityColumns"><section className="toolPanel"><div className="panelTitle"><div><Wrench size={20}/><div><h2>Checklist de cierre</h2><p>Decisiones que dejamos explícitas para producción.</p></div></div></div><div className="opsChecklist"><p><CheckCircle2/> Text-first: imágenes permanecen como herramienta secundaria.</p><p><CheckCircle2/> Compliance obligatorio antes de publicación.</p><p><CheckCircle2/> Facebook OAuth sustituye Graph API Explorer.</p><p><CheckCircle2/> Tokens de página se almacenan cifrados en servidor.</p><p><CheckCircle2/> Score editorial no se presenta como predicción de viralidad.</p><p><CheckCircle2/> Aprendizaje usa métricas reales cuando existen.</p></div></section><section className="toolPanel"><div className="panelTitle"><div><Settings2 size={20}/><div><h2>Páginas y operación</h2><p>Accesos útiles para la última revisión.</p></div></div></div><div className="qualityLinks"><a href="/privacy" target="_blank">Política de privacidad <ExternalLink size={14}/></a><a href="/terms" target="_blank">Condiciones <ExternalLink size={14}/></a><a href="/data-deletion" target="_blank">Eliminación de datos <ExternalLink size={14}/></a><button className="uiBtn uiBtnSecondary" onClick={()=>location.reload()}>Recargar aplicación</button></div></section></div>
  </>;
}
