"use client";

import { useEffect, useState } from "react";
import { BarChart3, CheckCircle2, Clipboard, FileText, Loader2, RefreshCw, Sparkles, TriangleAlert } from "lucide-react";

type Page={id:string;name:string};
export default function WeeklyReport(){
  const [pages,setPages]=useState<Page[]>([]);const [pageId,setPageId]=useState("");const [items,setItems]=useState<any[]>([]);const [current,setCurrent]=useState<any>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{void bootstrap()},[]);
  async function bootstrap(){try{const [pr,rr]=await Promise.all([fetch("/api/meta/pages",{cache:"no-store"}),fetch("/api/reports/weekly",{cache:"no-store"})]);const pd=await pr.json();const rd=await rr.json();const next=(pd.pages||[]).map((x:any)=>({id:String(x.id||x.page_id),name:String(x.name||x.page_name)}));setPages(next);if(next.length)setPageId(String(pd.activePageId||next[0].id));setItems(rd.items||[]);if(rd.items?.length)setCurrent(rd.items[0])}catch{}}
  async function generate(){setBusy(true);setMessage("");try{const r=await fetch("/api/reports/weekly",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pageId})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo generar el reporte.");const normalized={id:d.id,created_at:d.createdAt,page_id:d.context?.pageId,page_name:d.context?.pageName,metrics:d.context,report:d.report};setCurrent(normalized);setItems(c=>[normalized,...c].slice(0,8));setMessage("Reporte semanal actualizado.")}catch(e:any){setMessage(e?.message||"Falló el reporte.")}finally{setBusy(false)}}
  async function copy(){if(!current)return;const r=current.report||{};const text=`REPORTE SEMANAL · ${current.page_name||"Efímero"}\n\n${r.summary||""}\n\nQUÉ FUNCIONÓ\n${(r.wins||[]).map((x:string)=>`- ${x}`).join("\n")}\n\nRIESGOS\n${(r.risks||[]).map((x:string)=>`- ${x}`).join("\n")}\n\nSIGUIENTE SEMANA\n${(r.nextWeek||[]).map((x:string)=>`- ${x}`).join("\n")}\n\n${r.note||""}`;await navigator.clipboard.writeText(text);setMessage("Reporte copiado al portapapeles.")}
  const report=current?.report||{};const metrics=current?.metrics||{};
  return <>
    <div className="pageIntro"><div><span className="overline">BLOQUE 27 · REPORTE SEMANAL</span><h1>Qué aprendimos esta semana</h1><p>Resume desempeño observado, experimentos, fatiga y siguientes pruebas. Nunca convierte una muestra en una promesa de rendimiento.</p></div><div className="uiActionRow"><button className="uiBtn uiBtnSecondary" onClick={copy} disabled={!current}><Clipboard size={16}/> Copiar</button><button className="uiBtn uiBtnPrimary" onClick={generate} disabled={busy||!pageId}>{busy?<Loader2 className="spin" size={16}/>:<RefreshCw size={16}/>} Generar reporte</button></div></div>
    <section className="toolPanel weeklyToolbar"><label><span>Página</span><select value={pageId} onChange={e=>setPageId(e.target.value)}>{pages.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="reportHistory">{items.slice(0,5).map((x:any)=><button className={current?.id===x.id?"active":""} key={x.id} onClick={()=>setCurrent(x)}>{new Date(x.created_at).toLocaleDateString("es-MX")}</button>)}</div></section>
    {message&&<div className="inlineNotice">{message}</div>}
    {current?<><div className="weeklyMetrics"><article><span>Publicados</span><strong>{metrics.published||0}</strong><small>últimos 7 días</small></article><article><span>Compartidos</span><strong>{metrics.metrics?.shares||0}</strong><small>último snapshot/post</small></article><article><span>Comentarios</span><strong>{metrics.metrics?.comments||0}</strong><small>último snapshot/post</small></article><article><span>Compliance PASS</span><strong>{Math.round(Number(metrics.compliance?.passRate??1)*100)}%</strong><small>{metrics.compliance?.reviews||0} revisiones</small></article></div><section className="weeklyHero"><FileText size={28}/><div><span>RESUMEN DIRECTIVO</span><h2>{report.summary}</h2><p>{report.note}</p></div></section><div className="weeklyGrid"><ReportSection icon={<CheckCircle2/>} title="Qué funcionó" items={report.wins}/><ReportSection icon={<TriangleAlert/>} title="Riesgos / fatiga" items={report.risks}/><ReportSection icon={<BarChart3/>} title="Experimentos" items={report.experiments}/><ReportSection icon={<Sparkles/>} title="Qué probar después" items={report.nextWeek}/></div></>:<section className="emptyState"><FileText size={42}/><h2>Aún no hay reporte semanal</h2><p>Genera el primero cuando ya tengas publicaciones y snapshots de rendimiento.</p></section>}
  </>;
}
function ReportSection({icon,title,items=[]}:{icon:any;title:string;items?:string[]}){return <section className="toolPanel weeklySection"><div className="panelTitle"><div>{icon}<div><h2>{title}</h2></div></div></div><div className="reportList">{(items||[]).map((x,i)=><p key={i}><span>{i+1}</span>{x}</p>)}{!items?.length&&<div className="emptyInline">Sin señales suficientes en esta sección.</div>}</div></section>}
